#!/bin/sh

# if a module has a build dependency that is not in debian/alpine
# use this script to fetch/build/install them
#
# note that shared libraries produced as a result of this script will
# not be copied from the builder image to the resulting one, so you need to
# build them statically

echo "Work around Alpine's wget/403 issue with github.com by aliasing wget to busybox wget"
apk add wget
ln -sf /bin/busybox /usr/bin/wget

exit 0
